# Publish new releases to Bazel Central Registry.
# Mostly taken from https://github.com/bazel-contrib/rules-template/blob/main/.github/workflows/publish.yaml
name: Publish to BCR
on:
  # Run the publish workflow after a successful release
  # Will be triggered from the release.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      publish_token:
        required: true
  # Or we can run it manually through the GH UI
  workflow_dispatch:
    inputs:
      tag_name:
        description: git tag being released. Must already exist in the repository.
        required: true
        type: string
jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.1.0
    with:
      tag_name: ${{ inputs.tag_name }}
      # GitHub repository which is a fork of the upstream where the Pull Request will be opened.
      registry_fork: blorente/bazel-central-registry
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      # Necessary to push to the BCR fork, and to open a pull request against a registry
      publish_token: ${{ secrets.publish_token || secrets.BCR_PUBLISH_TOKEN }}
