"""GENERATED - This file was generated by install repository rule.
"""

load("@rules_cc//cc:defs.bzl", "cc_toolchain")
load("@%workspace_name%//:config.bzl", "cc_toolchain_config")

toolchain(
    name = "toolchain",
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    toolchain = ":cc_toolchain",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)

cc_toolchain(
    name = "cc_toolchain",
    all_files = "%all_files%",
    ar_files = "%ar_files%",
    as_files = "%as_files%",
    compiler_files = "%compiler_files%",
    dwp_files = "%dwp_files%",
    linker_files = "%linker_files%",
    objcopy_files = "%objcopy_files%",
    strip_files = "%strip_files%",
    supports_param_files = 0,
    toolchain_config = ":cc_toolchain_config",
    toolchain_identifier = "gcc-toolchain",
)

cc_toolchain_config(
    name = "cc_toolchain_config",
    tool_paths = %tool_paths%,
    hermetic_include_directories = %hermetic_include_directories%,
)
